# Numerical Python(Numpy) - Part1


### de facto standard (사실상의 표준)

In [ ]:
import numpy as np


In [ ]:
b = np.array([1, 2, 3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [ ]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array Shape

In [ ]:
# Vector (1차원)
vector = np.array([1,4,5,8])
vector
vector.shape

(4,)

In [ ]:
# Matrix (2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
# Tensor (3차원)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
tensor.shape

(2, 3, 4)

In [ ]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [ ]:
# element의 개수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [ ]:
# data type
# float32: 32bit로 표시 - single pre
# float64: 64bit로 표시
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

### reshape

In [ ]:
matrix.shape

(2, 3)

In [ ]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [ ]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)

matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [ ]:
matrix.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
matrix.reshape(3,-1).shape

(3, 2)

In [ ]:
tensor.reshape(4, -1).shape

(4, 6)

### flatten


In [ ]:
test_matrix = [[[1,2,3,4], [5,6,7,8]], [[2,3,4,5], [6,7,8,9]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor.flatten

<function ndarray.flatten>

## 3. Indexing & slicing

### Indexing

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix[0][1]

2

In [ ]:
matrix[0,1]

2

In [ ]:
tensor[1,1,2]

19

### Slicing

In [ ]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# 1, 3, 9, 11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
# x는 앞에 3열, y는 마지막 열
x, y = b[:, :-1], b[:, -1]