# Bag of Words

## 1. Count Vectorizer

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you.']

In [8]:
cvector = CountVectorizer()

In [9]:
cvector.fit(corpus)           # 학습
cvector.transform(corpus).toarray()    # 변환

array([[1, 1, 2, 1, 2, 1]])

In [10]:
cvector.vocabulary_     # 학습한 결과

{'because': 0, 'know': 1, 'love': 2, 'want': 3, 'you': 4, 'your': 5}

In [11]:
output = cvector.fit_transform(corpus).toarray()
output

array([[1, 1, 2, 1, 2, 1]])

- 불용어를 제거한 Bow

In [13]:
# 사용자 정의

text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [14]:
# Scikit-learn 제공

text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [18]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [19]:
# NLTK 제공

text=["Family is not an important thing. It's everything."]
sw = stopwords.words("english")
vect = CountVectorizer(stop_words =sw)
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [20]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key

In [21]:
get_word(2, vect.vocabulary_)

'important'

- N-gram

In [22]:
text1 = ['Machine learning is fun and not boring.']
text2 = ['Machine is boring and learning is not fun.']

In [24]:
vect = CountVectorizer()
print(vect.fit_transform(text1).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'machine': 5, 'learning': 4, 'is': 3, 'fun': 2, 'and': 0, 'not': 6, 'boring': 1}


In [25]:
vect = CountVectorizer()
print(vect.fit_transform(text2).toarray())
print(vect.vocabulary_)

[[1 1 1 2 1 1 1]]
{'machine': 5, 'is': 3, 'boring': 1, 'and': 0, 'learning': 4, 'not': 6, 'fun': 2}


In [26]:
# N-gram range: (1, 2)
vect = CountVectorizer(ngram_range=(1,2))
print(vect.fit_transform(text1).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]]
{'machine': 9, 'learning': 7, 'is': 5, 'fun': 3, 'and': 0, 'not': 11, 'boring': 2, 'machine learning': 10, 'learning is': 8, 'is fun': 6, 'fun and': 4, 'and not': 1, 'not boring': 12}


In [29]:
# N-gram range: (1, 3)
vect = CountVectorizer(ngram_range=(1,3), stop_words='english')
print(vect.fit_transform(text2).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1 1 1 1 1]]
{'machine': 6, 'boring': 0, 'learning': 4, 'fun': 3, 'machine boring': 7, 'boring learning': 1, 'learning fun': 5, 'machine boring learning': 8, 'boring learning fun': 2}


In [28]:
vect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

- DTM

In [30]:
corpus = [
          "you know i want your love",
          "I like you",
          "what should I do"
]
vect = CountVectorizer()
print(vect.fit_transform(corpus).toarray())
print(vect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


## TF-IDF Vectorizer

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [33]:
tvect = TfidfVectorizer(ngram_range=(1,2), stop_words='english')
print(tvect.fit_transform(corpus).toarray()).round(2))
print(tvect.vocabulary_)

[[0.4472136 0.4472136 0.        0.4472136 0.4472136 0.4472136]
 [0.        0.        1.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.       ]]
{'know': 0, 'want': 4, 'love': 3, 'know want': 1, 'want love': 5, 'like': 2}


In [34]:
tvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 2),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}